import { PropsWithChildren } from 'react';
import './global.css';
import { Toaster } from 'sonner';
import { ApolloWrapper } from '@/components/providers/ApolloWrapper';
import { UserAuthProvider } from '@/components/providers';
import { ConditionalLayout } from '@/components/layout/ConditionalLayout';

export const metadata = {
  title: 'Welcome to example-frontend',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body>
        <ApolloWrapper>
          <UserAuthProvider>
            <ConditionalLayout>{children}</ConditionalLayout>
          </UserAuthProvider>
        </ApolloWrapper>
        <Toaster richColors position="top-center" />
      </body>
    </html>
  );
};

export default RootLayout;
