import { PropsWithChildren } from 'react';
import './global.css';
import { ApolloWrapper, AuthProvider } from '@/components/providers';
import { Toaster } from '@/components/ui/sonner';

export const metadata = {
  title: 'Welcome to example-frontend',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body>
        <ApolloWrapper>
          <AuthProvider>
            <div>{children}</div>
            <Toaster />
          </AuthProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
