import { PropsWithChildren } from 'react';
import './global.css';
import { ApolloWrapper } from '@/components';
import { NavigationProvider } from '@/components';
import { AuthProvider } from '@/contexts/AuthContext';
import { ConditionalLayout } from '@/components/ConditionalLayout';

export const metadata = {
  title: 'Welcome to example-frontend',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body>
        <ApolloWrapper>
          <AuthProvider>
            <NavigationProvider>
              <ConditionalLayout>
                {children}
              </ConditionalLayout>
            </NavigationProvider>
          </AuthProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
