import { PropsWithChildren } from 'react';
import './global.css';
import { ApolloWrapper } from '@/components';
import { NavigationProvider } from '@/components';
import { Sidebar } from '@/components/Sidebar';
import { SearchSidebar } from '@/components/SearchSidebar';
import { MainLayout } from '@/components/MainLayout/MainLayout';

export const metadata = {
  title: 'Welcome to example-frontend',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body>
        <ApolloWrapper>
          <NavigationProvider>
            <div className="flex min-h-screen bg-white">
              <Sidebar />
              <SearchSidebar />
              <MainLayout>
                {children}
              </MainLayout>
            </div>
          </NavigationProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
};

export default RootLayout;