import { PropsWithChildren } from 'react';
import './global.css';
import { ApolloWrapper } from '@/components';
import { Sidebar } from '@/components';

export const metadata = {
  title: 'Welcome to example-frontend',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body>
        <ApolloWrapper>
          <div className="flex">
            <Sidebar />
            <main className="flex-1">
              {children}
            </main>
          </div>
        </ApolloWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
 