import { PropsWithChildren } from 'react';
import './global.css';
import { ApolloWrapper } from '@/components/providers';
import { Toaster } from 'sonner';
import { StepProvider } from '@/components/providers/stepProvider';
export const metadata = {
  title: 'Welcome to example-frontend',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body>
        <ApolloWrapper>
          <StepProvider>{children}</StepProvider>

          <Toaster position="top-right" richColors closeButton />
        </ApolloWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
