import { PropsWithChildren } from 'react';
import './global.css';
import { ApolloWrapper, AuthProvider } from '@/components/providers';
import { Toaster } from "sonner";
export const metadata = {
  title: 'Welcome to example-frontend',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ApolloWrapper>{children}
          <Toaster 
              position="top-right"  
              richColors             
              closeButton           
            />
          </ApolloWrapper>
        </AuthProvider>
      </body>
    </html>
  );
};

export default RootLayout;
