import { PropsWithChildren } from 'react';
import './global.css';
import RootLayoutComponent from './Home/navigation/components/RootLayout';

export const metadata = {
  title: 'Welcome to example-frontend',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body>
        <RootLayoutComponent>{children}</RootLayoutComponent>
      </body>
    </html>
  );
};

export default RootLayout;
