import React, { PropsWithChildren } from 'react';
import './global.css';
import { ApolloWrapper } from '@/components/providers';
import { Toaster } from '@/components/ui/sonner';
import { cookies } from 'next/headers';
import { MatchProvider } from '@/components/providers/MatchProvider';
import { OneUserProvider } from '@/components/providers/OneuserProvider';

export const metadata = {
  title: 'Welcome to example-frontend',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = async ({ children }: PropsWithChildren) => {
  const authToken = (await cookies().get('authToken')?.value) || '';
  return (
    <html lang="en">
      <body className="">
        <ApolloWrapper authToken={authToken}>
          <MatchProvider>
            <OneUserProvider>
              <div className="max-w-[1280px] mx-auto">
              {React.cloneElement(children as React.ReactElement, { authToken })}
                <Toaster />
              </div>
            </OneUserProvider>
          </MatchProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
