import { PropsWithChildren } from 'react';
import { AdminHeader } from './home/_components/AdminHeader';
import { AdminFooter } from './home/_components/AdminFooter';

export const metadata = {
  title: 'Welcome to example-frontend',
  description: 'Generated by create-nx-workspace',
};

const Layout = ({ children }: PropsWithChildren) => {
  return (
    <div className="bg-white">
      <AdminHeader />
      <div className="bg-gray-200">{children}</div>
      <AdminFooter />
    </div>
  );
};

export default Layout;
