import { PropsWithChildren } from 'react';
import './global.css';
import { ClerkProvider } from '@clerk/nextjs';
import ApolloProviderClient from '@/components/providers/ApolloClient';

export const metadata = {
  title: 'Tinder | 2CD',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="font-sans antialiased">
          <ApolloProviderClient>{children}</ApolloProviderClient>
        </body>
      </html>
    </ClerkProvider>
  );
};

export default RootLayout;
