import { PropsWithChildren } from 'react';
import '../global.css';
import { Toaster } from 'sonner';
import { ApolloWrapper } from '@/components/providers/ApolloWrapper';
import { UserAuthProvider } from '@/components/providers';
import { PublicHeader } from '@/components/landing-page/PublicHeader';
import { PublicFooter } from '@/components/landing-page/PublicFooter';

export const metadata = {
  title: 'Welcome to example-frontend',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body>
        <ApolloWrapper>
          <UserAuthProvider>
            <PublicHeader />
            {children}
            <PublicFooter />
          </UserAuthProvider>
        </ApolloWrapper>
        <Toaster richColors position="top-center" />
      </body>
    </html>
  );
};

export default RootLayout;
