import { PropsWithChildren } from 'react';
import './global.css';
import { ApolloWrapper } from '@/components/providers';
import FooterHome from '@/components/FooterHome';
import Header from '@/components/Header';
<<<<<<< HEAD

export const metadata = {
  title: 'Welcome to example-frontend',
  description: 'Generated by create-nx-workspace',
};
=======
import HotelDetail from './(client)/hotel-detail/HotelDetail';
import { ToastContainer } from 'react-toastify';
>>>>>>> origin/main

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body>
        <ApolloWrapper>
          <Header />
<<<<<<< HEAD
=======
          <HotelDetail />
>>>>>>> origin/main
          {children}
          <FooterHome />
          <ToastContainer />
        </ApolloWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
