import { demoImage } from '@/components/userProfile/mock-images';

export interface Story {
  id: number;
  username: string;
  avatar: string;
  hasStory: boolean;
}

export interface Suggestion {
  id: number;
  username: string;
  description: string;
  avatar: string;
}

export interface Post {
  id: number;
  username: string;
  timeAgo: string;
  image: string;
  likes: number;
  caption: string;
  comments: number;
}

export const stories: Story[] = [
  { id: 1, username: 'defavours', avatar: demoImage, hasStory: true },
  { id: 2, username: 'defavours', avatar: demoImage, hasStory: true },
  { id: 3, username: 'defavours', avatar: demoImage, hasStory: true },
  { id: 4, username: 'defavours', avatar: demoImage, hasStory: true },
  { id: 5, username: 'defavours', avatar: demoImage, hasStory: true },
  { id: 6, username: 'defavours', avatar: demoImage, hasStory: true },
  { id: 7, username: 'travel_lover', avatar: demoImage, hasStory: true },
  { id: 8, username: 'foodie_paradise', avatar: demoImage, hasStory: true },
  { id: 9, username: 'fitness_motivation', avatar: demoImage, hasStory: true },
  { id: 10, username: 'art_creations', avatar: demoImage, hasStory: true },
  { id: 11, username: 'music_vibes', avatar: demoImage, hasStory: true },
  { id: 12, username: 'fashion_style', avatar: demoImage, hasStory: true },
  { id: 13, username: 'tech_news', avatar: demoImage, hasStory: true },
  { id: 14, username: 'nature_photography', avatar: demoImage, hasStory: true },
  { id: 15, username: 'coffee_addict', avatar: demoImage, hasStory: true },
  { id: 16, username: 'bookworm_life', avatar: demoImage, hasStory: true },
  { id: 17, username: 'pet_lovers', avatar: demoImage, hasStory: true },
  { id: 18, username: 'yoga_zen', avatar: demoImage, hasStory: true },
  { id: 19, username: 'gaming_community', avatar: demoImage, hasStory: true },
  { id: 20, username: 'cooking_master', avatar: demoImage, hasStory: true },
  { id: 21, username: 'adventure_seeker', avatar: demoImage, hasStory: true },
  { id: 22, username: 'beauty_tips', avatar: demoImage, hasStory: true },
  { id: 23, username: 'home_decor', avatar: demoImage, hasStory: true },
  { id: 24, username: 'car_enthusiast', avatar: demoImage, hasStory: true },
  { id: 25, username: 'sports_fanatic', avatar: demoImage, hasStory: true },
  { id: 26, username: 'movie_buff', avatar: demoImage, hasStory: true },
  { id: 27, username: 'plant_parent', avatar: demoImage, hasStory: true },
  { id: 28, username: 'craft_ideas', avatar: demoImage, hasStory: true },
  { id: 29, username: 'dance_passion', avatar: demoImage, hasStory: true },
  { id: 30, username: 'photography_pro', avatar: demoImage, hasStory: true },
  { id: 31, username: 'healthy_living', avatar: demoImage, hasStory: true },
  { id: 32, username: 'travel_photography', avatar: demoImage, hasStory: true },
  { id: 33, username: 'street_art', avatar: demoImage, hasStory: true },
  { id: 34, username: 'vintage_finds', avatar: demoImage, hasStory: true },
  { id: 35, username: 'modern_architecture', avatar: demoImage, hasStory: true },
  { id: 36, username: 'street_fashion', avatar: demoImage, hasStory: true },
  { id: 37, username: 'food_photography', avatar: demoImage, hasStory: true },
  { id: 38, username: 'minimalist_life', avatar: demoImage, hasStory: true },
  { id: 39, username: 'creative_design', avatar: demoImage, hasStory: true },
  { id: 40, username: 'wellness_journey', avatar: demoImage, hasStory: true },
  { id: 41, username: 'urban_explorer', avatar: demoImage, hasStory: true },
  { id: 42, username: 'eco_friendly', avatar: demoImage, hasStory: true },
  { id: 43, username: 'digital_art', avatar: demoImage, hasStory: true },
  { id: 44, username: 'classic_cars', avatar: demoImage, hasStory: true },
  { id: 45, username: 'luxury_lifestyle', avatar: demoImage, hasStory: true },
  { id: 46, username: 'budget_travel', avatar: demoImage, hasStory: true },
  { id: 47, username: 'homemade_crafts', avatar: demoImage, hasStory: true },
  { id: 48, username: 'fitness_challenge', avatar: demoImage, hasStory: true },
  { id: 49, username: 'art_gallery', avatar: demoImage, hasStory: true },
  { id: 50, username: 'music_production', avatar: demoImage, hasStory: true },
  { id: 51, username: 'fashion_blogger', avatar: demoImage, hasStory: true },
  { id: 52, username: 'tech_reviews', avatar: demoImage, hasStory: true },
  { id: 53, username: 'wildlife_photography', avatar: demoImage, hasStory: true },
  { id: 54, username: 'coffee_culture', avatar: demoImage, hasStory: true },
  { id: 55, username: 'literary_quotes', avatar: demoImage, hasStory: true },
  { id: 56, username: 'pet_adventures', avatar: demoImage, hasStory: true },
  { id: 57, username: 'meditation_guide', avatar: demoImage, hasStory: true },
  { id: 58, username: 'esports_news', avatar: demoImage, hasStory: true },
  { id: 59, username: 'culinary_arts', avatar: demoImage, hasStory: true },
  { id: 60, username: 'hiking_trails', avatar: demoImage, hasStory: true },
  { id: 61, username: 'skincare_routine', avatar: demoImage, hasStory: true },
  { id: 62, username: 'interior_design', avatar: demoImage, hasStory: true },
  { id: 63, username: 'supercar_spotting', avatar: demoImage, hasStory: true },
  { id: 64, username: 'olympic_sports', avatar: demoImage, hasStory: true },
  { id: 65, username: 'indie_films', avatar: demoImage, hasStory: true },
  { id: 66, username: 'garden_tips', avatar: demoImage, hasStory: true },
  { id: 67, username: 'diy_projects', avatar: demoImage, hasStory: true },
  { id: 68, username: 'dance_challenge', avatar: demoImage, hasStory: true },
  { id: 69, username: 'portrait_photography', avatar: demoImage, hasStory: true },
  { id: 70, username: 'nutrition_facts', avatar: demoImage, hasStory: true },
  { id: 71, username: 'landscape_views', avatar: demoImage, hasStory: true },
  { id: 72, username: 'graffiti_art', avatar: demoImage, hasStory: true },
  { id: 73, username: 'retro_style', avatar: demoImage, hasStory: true },
  { id: 74, username: 'contemporary_art', avatar: demoImage, hasStory: true },
  { id: 75, username: 'street_style', avatar: demoImage, hasStory: true },
  { id: 76, username: 'foodie_adventures', avatar: demoImage, hasStory: true },
  { id: 77, username: 'simple_living', avatar: demoImage, hasStory: true },
  { id: 78, username: 'graphic_design', avatar: demoImage, hasStory: true },
  { id: 79, username: 'mental_health', avatar: demoImage, hasStory: true },
  { id: 80, username: 'city_discovery', avatar: demoImage, hasStory: true },
  { id: 81, username: 'sustainable_living', avatar: demoImage, hasStory: true },
  { id: 82, username: 'illustration_art', avatar: demoImage, hasStory: true },
  { id: 83, username: 'vintage_cars', avatar: demoImage, hasStory: true },
  { id: 84, username: 'high_end_fashion', avatar: demoImage, hasStory: true },
  { id: 85, username: 'backpacking_tips', avatar: demoImage, hasStory: true },
  { id: 86, username: 'handmade_goods', avatar: demoImage, hasStory: true },
  { id: 87, username: 'workout_motivation', avatar: demoImage, hasStory: true },
  { id: 88, username: 'art_exhibition', avatar: demoImage, hasStory: true },
  { id: 89, username: 'music_discovery', avatar: demoImage, hasStory: true },
  { id: 90, username: 'style_inspiration', avatar: demoImage, hasStory: true },
  { id: 91, username: 'gadget_reviews', avatar: demoImage, hasStory: true },
  { id: 92, username: 'nature_walks', avatar: demoImage, hasStory: true },
  { id: 93, username: 'brewery_tours', avatar: demoImage, hasStory: true },
  { id: 94, username: 'book_recommendations', avatar: demoImage, hasStory: true },
  { id: 95, username: 'animal_friends', avatar: demoImage, hasStory: true },
  { id: 96, username: 'mindfulness_practice', avatar: demoImage, hasStory: true },
  { id: 97, username: 'gaming_streams', avatar: demoImage, hasStory: true },
  { id: 98, username: 'chef_secrets', avatar: demoImage, hasStory: true },
  { id: 99, username: 'mountain_climbing', avatar: demoImage, hasStory: true },
  { id: 100, username: 'beauty_tutorials', avatar: demoImage, hasStory: true },
];

export const suggestions: Suggestion[] = [
  { id: 1, username: 'linktr', description: 'Follows you', avatar: '🌱' },
  { id: 2, username: 'baylejf', description: 'Followed by gphiemr', avatar: '👤' },
  { id: 3, username: 'wilfred30', description: 'Followed by gphiemr', avatar: '📸' },
  { id: 4, username: 'ghostly_dolls', description: 'Follows you', avatar: '👻' },
  { id: 5, username: 'n3g4t1v3_5p4c3', description: 'New to Instagram', avatar: '🎮' },
  { id: 6, username: 'travel_enthusiast', description: 'Followed by adventure_seeker', avatar: '✈️' },
  { id: 7, username: 'food_lover_123', description: 'Follows you', avatar: '🍕' },
  { id: 8, username: 'fitness_guru', description: 'Followed by healthy_living', avatar: '💪' },
  { id: 9, username: 'art_creator', description: 'New to Instagram', avatar: '🎨' },
  { id: 10, username: 'music_producer', description: 'Followed by music_vibes', avatar: '🎵' },
  { id: 11, username: 'fashion_icon', description: 'Follows you', avatar: '👗' },
  { id: 12, username: 'tech_geek', description: 'Followed by tech_news', avatar: '💻' },
  { id: 13, username: 'nature_lover', description: 'New to Instagram', avatar: '🌿' },
  { id: 14, username: 'coffee_master', description: 'Followed by coffee_addict', avatar: '☕' },
  { id: 15, username: 'book_nerd', description: 'Follows you', avatar: '📚' },
  { id: 16, username: 'pet_whisperer', description: 'Followed by pet_lovers', avatar: '🐕' },
  { id: 17, username: 'yoga_instructor', description: 'New to Instagram', avatar: '🧘' },
  { id: 18, username: 'gamer_pro', description: 'Followed by gaming_community', avatar: '🎮' },
  { id: 19, username: 'chef_expert', description: 'Follows you', avatar: '👨‍🍳' },
  { id: 20, username: 'adventure_time', description: 'Followed by adventure_seeker', avatar: '🏔️' },
  { id: 21, username: 'beauty_guru', description: 'New to Instagram', avatar: '💄' },
  { id: 22, username: 'home_designer', description: 'Followed by home_decor', avatar: '🏠' },
  { id: 23, username: 'car_collector', description: 'Follows you', avatar: '🚗' },
  { id: 24, username: 'sports_champ', description: 'Followed by sports_fanatic', avatar: '⚽' },
  { id: 25, username: 'movie_critic', description: 'New to Instagram', avatar: '🎬' },
  { id: 26, username: 'plant_expert', description: 'Followed by plant_parent', avatar: '🌱' },
  { id: 27, username: 'craft_master', description: 'Follows you', avatar: '🧶' },
  { id: 28, username: 'dance_star', description: 'Followed by dance_passion', avatar: '💃' },
  { id: 29, username: 'photo_pro', description: 'New to Instagram', avatar: '📷' },
  { id: 30, username: 'health_coach', description: 'Followed by healthy_living', avatar: '🏃' },
  { id: 31, username: 'landscape_pro', description: 'Follows you', avatar: '🏞️' },
  { id: 32, username: 'street_artist', description: 'Followed by street_art', avatar: '🎭' },
  { id: 33, username: 'vintage_hunter', description: 'New to Instagram', avatar: '🕰️' },
  { id: 34, username: 'architect_design', description: 'Followed by modern_architecture', avatar: '🏛️' },
  { id: 35, username: 'style_blogger', description: 'Follows you', avatar: '👔' },
  { id: 36, username: 'food_photographer', description: 'Followed by food_photography', avatar: '🍽️' },
  { id: 37, username: 'minimalist_life', description: 'New to Instagram', avatar: '⚪' },
  { id: 38, username: 'creative_mind', description: 'Followed by creative_design', avatar: '🎯' },
  { id: 39, username: 'wellness_expert', description: 'Follows you', avatar: '🧘‍♀️' },
  { id: 40, username: 'city_explorer', description: 'Followed by urban_explorer', avatar: '🌆' },
  { id: 41, username: 'eco_warrior', description: 'New to Instagram', avatar: '🌍' },
  { id: 42, username: 'digital_artist', description: 'Followed by digital_art', avatar: '🖥️' },
  { id: 43, username: 'classic_car_lover', description: 'Follows you', avatar: '🚙' },
  { id: 44, username: 'luxury_life', description: 'Followed by luxury_lifestyle', avatar: '💎' },
  { id: 45, username: 'budget_traveler', description: 'New to Instagram', avatar: '🎒' },
  { id: 46, username: 'handmade_creator', description: 'Followed by homemade_crafts', avatar: '✂️' },
  { id: 47, username: 'fitness_trainer', description: 'Follows you', avatar: '🏋️' },
  { id: 48, username: 'art_curator', description: 'Followed by art_gallery', avatar: '🖼️' },
  { id: 49, username: 'music_artist', description: 'New to Instagram', avatar: '🎤' },
  { id: 50, username: 'fashion_designer', description: 'Followed by fashion_blogger', avatar: '👘' },
  { id: 51, username: 'tech_reviewer', description: 'Follows you', avatar: '📱' },
  { id: 52, username: 'wildlife_photographer', description: 'Followed by wildlife_photography', avatar: '🦁' },
  { id: 53, username: 'coffee_roaster', description: 'New to Instagram', avatar: '🫘' },
  { id: 54, username: 'literary_author', description: 'Followed by literary_quotes', avatar: '✍️' },
  { id: 55, username: 'pet_trainer', description: 'Follows you', avatar: '🐈' },
  { id: 56, username: 'meditation_teacher', description: 'Followed by meditation_guide', avatar: '🧘‍♂️' },
  { id: 57, username: 'esports_player', description: 'New to Instagram', avatar: '🎯' },
  { id: 58, username: 'culinary_chef', description: 'Followed by culinary_arts', avatar: '👩‍🍳' },
  { id: 59, username: 'hiking_guide', description: 'Follows you', avatar: '🥾' },
  { id: 60, username: 'skincare_expert', description: 'Followed by skincare_routine', avatar: '🧴' },
  { id: 61, username: 'interior_stylist', description: 'New to Instagram', avatar: '🪑' },
  { id: 62, username: 'supercar_spotter', description: 'Followed by supercar_spotting', avatar: '🏎️' },
  { id: 63, username: 'olympic_athlete', description: 'Follows you', avatar: '🥇' },
  { id: 64, username: 'indie_director', description: 'Followed by indie_films', avatar: '🎥' },
  { id: 65, username: 'garden_expert', description: 'New to Instagram', avatar: '🌺' },
  { id: 66, username: 'diy_master', description: 'Followed by diy_projects', avatar: '🔨' },
  { id: 67, username: 'dance_instructor', description: 'Follows you', avatar: '🕺' },
  { id: 68, username: 'portrait_artist', description: 'Followed by portrait_photography', avatar: '👤' },
  { id: 69, username: 'nutritionist', description: 'New to Instagram', avatar: '🥗' },
  { id: 70, username: 'landscape_artist', description: 'Followed by landscape_views', avatar: '🏔️' },
  { id: 71, username: 'graffiti_writer', description: 'Follows you', avatar: '🎨' },
  { id: 72, username: 'retro_collector', description: 'Followed by retro_style', avatar: '📻' },
  { id: 73, username: 'contemporary_curator', description: 'New to Instagram', avatar: '🎭' },
  { id: 74, username: 'street_style_icon', description: 'Followed by street_style', avatar: '👕' },
  { id: 75, username: 'foodie_explorer', description: 'Follows you', avatar: '🍜' },
  { id: 76, username: 'simple_living_guide', description: 'Followed by simple_living', avatar: '🌿' },
  { id: 77, username: 'graphic_designer', description: 'New to Instagram', avatar: '🎨' },
  { id: 78, username: 'mental_health_advocate', description: 'Followed by mental_health', avatar: '🧠' },
  { id: 79, username: 'urban_photographer', description: 'Follows you', avatar: '🏙️' },
  { id: 80, username: 'sustainability_expert', description: 'Followed by sustainable_living', avatar: '♻️' },
  { id: 81, username: 'illustration_artist', description: 'New to Instagram', avatar: '✏️' },
  { id: 82, username: 'vintage_car_collector', description: 'Followed by vintage_cars', avatar: '🚗' },
  { id: 83, username: 'high_fashion_model', description: 'Follows you', avatar: '👠' },
  { id: 84, username: 'backpacking_guide', description: 'Followed by backpacking_tips', avatar: '🎒' },
  { id: 85, username: 'handmade_artisan', description: 'New to Instagram', avatar: '🧵' },
  { id: 86, username: 'workout_coach', description: 'Followed by workout_motivation', avatar: '🏃‍♀️' },
  { id: 87, username: 'art_exhibition_curator', description: 'Follows you', avatar: '🖼️' },
  { id: 88, username: 'music_discoverer', description: 'Followed by music_discovery', avatar: '🎧' },
  { id: 89, username: 'style_influencer', description: 'New to Instagram', avatar: '👗' },
  { id: 90, username: 'gadget_reviewer', description: 'Followed by gadget_reviews', avatar: '📱' },
  { id: 91, username: 'nature_walker', description: 'Follows you', avatar: '🌲' },
  { id: 92, username: 'brewery_owner', description: 'Followed by brewery_tours', avatar: '🍺' },
  { id: 93, username: 'book_curator', description: 'New to Instagram', avatar: '📖' },
  { id: 94, username: 'animal_rescuer', description: 'Followed by animal_friends', avatar: '🐾' },
  { id: 95, username: 'mindfulness_coach', description: 'Follows you', avatar: '🧘‍♀️' },
  { id: 96, username: 'gaming_streamer', description: 'Followed by gaming_streams', avatar: '🎮' },
  { id: 97, username: 'chef_instructor', description: 'New to Instagram', avatar: '👨‍🍳' },
  { id: 98, username: 'mountain_guide', description: 'Followed by mountain_climbing', avatar: '⛰️' },
  { id: 99, username: 'beauty_influencer', description: 'Follows you', avatar: '💋' },
  { id: 100, username: 'lifestyle_blogger', description: 'New to Instagram', avatar: '✨' },
];

export const posts: Post[] = [
  {
    id: 1,
    username: 'defavours',
    timeAgo: '5h',
    image: 'https://carveyourcraving.com/wp-content/uploads/2021/06/chocolate-icecream-in-an-icecream-maker.jpg',
    likes: 741368,
    caption: '@defavours love these after a hard day of work. #missonsummer #strawberry is the best flavor',
    comments: 13394,
  },
  {
    id: 2,
    username: 'travel_lover',
    timeAgo: '2h',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    likes: 15420,
    caption: 'Sunset views from the mountains! 🌄 #travel #adventure #nature #photography',
    comments: 892,
  },
  {
    id: 3,
    username: 'foodie_paradise',
    timeAgo: '1h',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=800',
    likes: 8934,
    caption: 'Homemade pizza night! 🍕 Nothing beats fresh ingredients #foodie #homemade #pizza',
    comments: 456,
  },
  {
    id: 4,
    username: 'fitness_motivation',
    timeAgo: '30m',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
    likes: 12567,
    caption: 'Morning workout complete! 💪 Consistency is key #fitness #motivation #workout',
    comments: 234,
  },
  {
    id: 5,
    username: 'art_creations',
    timeAgo: '4h',
    image: 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800',
    likes: 6789,
    caption: 'New watercolor piece inspired by spring flowers 🌸 #art #watercolor #spring',
    comments: 123,
  },
  {
    id: 6,
    username: 'music_vibes',
    timeAgo: '6h',
    image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
    likes: 23456,
    caption: 'Studio session today! New track coming soon 🎵 #music #studio #newmusic',
    comments: 567,
  },
  {
    id: 7,
    username: 'fashion_style',
    timeAgo: '3h',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',
    likes: 18923,
    caption: 'Spring collection preview! What do you think? 👗 #fashion #spring #style',
    comments: 789,
  },
  {
    id: 8,
    username: 'tech_news',
    timeAgo: '8h',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800',
    likes: 45678,
    caption: 'Latest tech innovations that will change everything! 💻 #tech #innovation #future',
    comments: 1234,
  },
  {
    id: 9,
    username: 'nature_photography',
    timeAgo: '12h',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    likes: 34567,
    caption: 'Captured this amazing landscape at golden hour 📸 #nature #photography #landscape',
    comments: 456,
  },
  {
    id: 10,
    username: 'coffee_addict',
    timeAgo: '1h',
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800',
    likes: 9876,
    caption: 'Perfect latte art this morning! ☕ #coffee #latteart #morning',
    comments: 234,
  },
  {
    id: 11,
    username: 'bookworm_life',
    timeAgo: '5h',
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800',
    likes: 5678,
    caption: 'Current read: The Midnight Library 📚 Highly recommend! #books #reading #bookworm',
    comments: 123,
  },
  {
    id: 12,
    username: 'pet_lovers',
    timeAgo: '2h',
    image: 'https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=800',
    likes: 23456,
    caption: 'My little buddy enjoying the sunshine! 🐕 #pets #dogs #sunshine',
    comments: 456,
  },
  {
    id: 13,
    username: 'yoga_zen',
    timeAgo: '7h',
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
    likes: 12345,
    caption: 'Morning yoga flow to start the day right 🧘‍♀️ #yoga #morning #zen',
    comments: 234,
  },
  {
    id: 14,
    username: 'gaming_community',
    timeAgo: '4h',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800',
    likes: 34567,
    caption: 'New gaming setup is complete! 🎮 #gaming #setup #gamer',
    comments: 567,
  },
  {
    id: 15,
    username: 'cooking_master',
    timeAgo: '6h',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
    likes: 15678,
    caption: 'Homemade pasta from scratch! 🍝 #cooking #homemade #pasta',
    comments: 345,
  },
  {
    id: 16,
    username: 'adventure_seeker',
    timeAgo: '1d',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    likes: 45678,
    caption: 'Hiking adventure in the mountains! 🏔️ #adventure #hiking #mountains',
    comments: 789,
  },
  {
    id: 17,
    username: 'beauty_tips',
    timeAgo: '3h',
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800',
    likes: 23456,
    caption: 'Skincare routine that changed my life! ✨ #beauty #skincare #routine',
    comments: 456,
  },
  {
    id: 18,
    username: 'home_decor',
    timeAgo: '8h',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
    likes: 18923,
    caption: 'Living room makeover complete! 🏠 #homedecor #interior #makeover',
    comments: 234,
  },
  {
    id: 19,
    username: 'car_enthusiast',
    timeAgo: '5h',
    image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
    likes: 34567,
    caption: 'Spotted this beauty today! 🚗 #cars #supercar #spotting',
    comments: 567,
  },
  {
    id: 20,
    username: 'sports_fanatic',
    timeAgo: '2h',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
    likes: 23456,
    caption: "Game day! Let's go team! ⚽ #sports #gameday #team",
    comments: 456,
  },
  {
    id: 21,
    username: 'movie_buff',
    timeAgo: '6h',
    image: 'https://images.unsplash.com/photo-1489599835382-6746f141f94b?w=800',
    likes: 12345,
    caption: 'Movie night with the best popcorn! 🍿 #movies #movienight #popcorn',
    comments: 234,
  },
  {
    id: 22,
    username: 'plant_parent',
    timeAgo: '4h',
    image: 'https://images.unsplash.com/photo-1466781783364-36c955e42a7f?w=800',
    likes: 9876,
    caption: 'New plant babies! 🌱 #plants #plantparent #greenery',
    comments: 123,
  },
  {
    id: 23,
    username: 'craft_ideas',
    timeAgo: '7h',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800',
    likes: 5678,
    caption: 'DIY project: Handmade jewelry! 💍 #crafts #diy #jewelry',
    comments: 123,
  },
  {
    id: 24,
    username: 'dance_passion',
    timeAgo: '3h',
    image: 'https://images.unsplash.com/photo-1504609773096-104ff2c73ba4?w=800',
    likes: 23456,
    caption: 'Dance practice session! 💃 #dance #practice #passion',
    comments: 456,
  },
  {
    id: 25,
    username: 'photography_pro',
    timeAgo: '9h',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    likes: 34567,
    caption: 'Street photography in the city 📸 #photography #street #city',
    comments: 567,
  },
  {
    id: 26,
    username: 'healthy_living',
    timeAgo: '1h',
    image: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800',
    likes: 15678,
    caption: 'Healthy breakfast bowl! 🥗 #healthy #breakfast #nutrition',
    comments: 234,
  },
  {
    id: 27,
    username: 'travel_photography',
    timeAgo: '12h',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    likes: 45678,
    caption: 'Travel photography from around the world! 🌍 #travel #photography #world',
    comments: 789,
  },
  {
    id: 28,
    username: 'street_art',
    timeAgo: '5h',
    image: 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800',
    likes: 23456,
    caption: 'Amazing street art found today! 🎨 #streetart #urban #art',
    comments: 456,
  },
  {
    id: 29,
    username: 'vintage_finds',
    timeAgo: '8h',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',
    likes: 12345,
    caption: 'Vintage shopping haul! 🕰️ #vintage #shopping #fashion',
    comments: 234,
  },
  {
    id: 30,
    username: 'modern_architecture',
    timeAgo: '6h',
    image: 'https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=800',
    likes: 23456,
    caption: 'Modern architecture that inspires! 🏛️ #architecture #modern #design',
    comments: 345,
  },
  {
    id: 31,
    username: 'street_fashion',
    timeAgo: '4h',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',
    likes: 18923,
    caption: 'Street style inspiration! 👕 #streetstyle #fashion #inspiration',
    comments: 234,
  },
  {
    id: 32,
    username: 'food_photography',
    timeAgo: '2h',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=800',
    likes: 23456,
    caption: 'Food photography session! 📸 #foodphotography #food #photography',
    comments: 456,
  },
  {
    id: 33,
    username: 'minimalist_life',
    timeAgo: '7h',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
    likes: 9876,
    caption: 'Minimalist home design! ⚪ #minimalist #design #home',
    comments: 123,
  },
  {
    id: 34,
    username: 'creative_design',
    timeAgo: '5h',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800',
    likes: 15678,
    caption: 'Creative design process! 🎯 #design #creative #process',
    comments: 234,
  },
  {
    id: 35,
    username: 'wellness_journey',
    timeAgo: '3h',
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
    likes: 12345,
    caption: 'Wellness journey continues! 🧘‍♀️ #wellness #journey #health',
    comments: 234,
  },
  {
    id: 36,
    username: 'urban_explorer',
    timeAgo: '9h',
    image: 'https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=800',
    likes: 23456,
    caption: 'Urban exploration adventure! 🌆 #urban #exploration #city',
    comments: 345,
  },
  {
    id: 37,
    username: 'eco_friendly',
    timeAgo: '6h',
    image: 'https://images.unsplash.com/photo-1466781783364-36c955e42a7f?w=800',
    likes: 15678,
    caption: 'Eco-friendly lifestyle tips! 🌍 #eco #friendly #lifestyle',
    comments: 234,
  },
  {
    id: 38,
    username: 'digital_art',
    timeAgo: '4h',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800',
    likes: 23456,
    caption: 'Digital art creation! 🖥️ #digitalart #art #creation',
    comments: 456,
  },
  {
    id: 39,
    username: 'classic_cars',
    timeAgo: '8h',
    image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
    likes: 34567,
    caption: 'Classic car show! 🚗 #classiccars #cars #show',
    comments: 567,
  },
  {
    id: 40,
    username: 'luxury_lifestyle',
    timeAgo: '5h',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
    likes: 45678,
    caption: 'Luxury lifestyle moments! 💎 #luxury #lifestyle #moments',
    comments: 789,
  },
  {
    id: 41,
    username: 'budget_travel',
    timeAgo: '12h',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    likes: 23456,
    caption: 'Budget travel tips! 💰 #budget #travel #tips',
    comments: 456,
  },
  {
    id: 42,
    username: 'homemade_crafts',
    timeAgo: '7h',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800',
    likes: 12345,
    caption: 'Homemade craft projects! ✂️ #homemade #crafts #projects',
    comments: 234,
  },
  {
    id: 43,
    username: 'fitness_challenge',
    timeAgo: '3h',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
    likes: 23456,
    caption: '30-day fitness challenge! 💪 #fitness #challenge #motivation',
    comments: 456,
  },
  {
    id: 44,
    username: 'art_gallery',
    timeAgo: '6h',
    image: 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800',
    likes: 34567,
    caption: 'Art gallery opening! 🖼️ #art #gallery #opening',
    comments: 567,
  },
  {
    id: 45,
    username: 'music_production',
    timeAgo: '4h',
    image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
    likes: 23456,
    caption: 'Music production in progress! 🎵 #music #production #studio',
    comments: 456,
  },
  {
    id: 46,
    username: 'fashion_blogger',
    timeAgo: '8h',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',
    likes: 18923,
    caption: 'Fashion blogger life! 👗 #fashion #blogger #style',
    comments: 234,
  },
  {
    id: 47,
    username: 'tech_reviews',
    timeAgo: '5h',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800',
    likes: 34567,
    caption: 'Latest tech review! 💻 #tech #review #latest',
    comments: 567,
  },
  {
    id: 48,
    username: 'wildlife_photography',
    timeAgo: '9h',
    image: 'https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=800',
    likes: 45678,
    caption: 'Wildlife photography adventure! 🦁 #wildlife #photography #adventure',
    comments: 789,
  },
  {
    id: 49,
    username: 'coffee_culture',
    timeAgo: '2h',
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800',
    likes: 15678,
    caption: 'Coffee culture around the world! ☕ #coffee #culture #world',
    comments: 234,
  },
  {
    id: 50,
    username: 'literary_quotes',
    timeAgo: '6h',
    image: 'https://images.unsplash.com/photo-1489599835382-6746f141f94b?w=800',
    likes: 12345,
    caption: 'Inspiring literary quotes! ✍️ #literary #quotes #inspiration',
    comments: 234,
  },
  {
    id: 51,
    username: 'pet_adventures',
    timeAgo: '4h',
    image: 'https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=800',
    likes: 23456,
    caption: 'Pet adventure day! 🐾 #pets #adventure #fun',
    comments: 456,
  },
  {
    id: 52,
    username: 'meditation_guide',
    timeAgo: '8h',
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
    likes: 12345,
    caption: 'Meditation guide for beginners! 🧘‍♂️ #meditation #guide #beginners',
    comments: 234,
  },
  {
    id: 53,
    username: 'esports_news',
    timeAgo: '3h',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800',
    likes: 34567,
    caption: 'Latest esports tournament results! 🎯 #esports #tournament #gaming',
    comments: 567,
  },
  {
    id: 54,
    username: 'culinary_arts',
    timeAgo: '6h',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
    likes: 23456,
    caption: 'Culinary arts masterclass! 👩‍🍳 #culinary #arts #masterclass',
    comments: 456,
  },
  {
    id: 55,
    username: 'hiking_trails',
    timeAgo: '12h',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    likes: 45678,
    caption: 'Best hiking trails this season! 🥾 #hiking #trails #nature',
    comments: 789,
  },
  {
    id: 56,
    username: 'skincare_routine',
    timeAgo: '2h',
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800',
    likes: 18923,
    caption: 'Skincare routine that works! ✨ #skincare #routine #beauty',
    comments: 234,
  },
  {
    id: 57,
    username: 'interior_design',
    timeAgo: '7h',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
    likes: 23456,
    caption: 'Interior design inspiration! 🏠 #interior #design #inspiration',
    comments: 345,
  },
  {
    id: 58,
    username: 'supercar_spotting',
    timeAgo: '5h',
    image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
    likes: 34567,
    caption: 'Supercar spotting in the city! 🏎️ #supercar #spotting #city',
    comments: 567,
  },
  {
    id: 59,
    username: 'olympic_sports',
    timeAgo: '9h',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
    likes: 45678,
    caption: 'Olympic sports highlights! 🥇 #olympic #sports #highlights',
    comments: 789,
  },
  {
    id: 60,
    username: 'indie_films',
    timeAgo: '4h',
    image: 'https://images.unsplash.com/photo-1489599835382-6746f141f94b?w=800',
    likes: 12345,
    caption: 'Indie film recommendations! 🎬 #indie #films #recommendations',
    comments: 234,
  },
  {
    id: 61,
    username: 'garden_tips',
    timeAgo: '6h',
    image: 'https://images.unsplash.com/photo-1466781783364-36c955e42a7f?w=800',
    likes: 9876,
    caption: 'Garden tips for beginners! 🌺 #garden #tips #beginners',
    comments: 123,
  },
  {
    id: 62,
    username: 'diy_projects',
    timeAgo: '3h',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800',
    likes: 15678,
    caption: 'DIY project tutorial! 🔨 #diy #projects #tutorial',
    comments: 234,
  },
  {
    id: 63,
    username: 'dance_challenge',
    timeAgo: '8h',
    image: 'https://images.unsplash.com/photo-1504609773096-104ff2c73ba4?w=800',
    likes: 23456,
    caption: 'Dance challenge accepted! 💃 #dance #challenge #fun',
    comments: 456,
  },
  {
    id: 64,
    username: 'portrait_photography',
    timeAgo: '5h',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    likes: 23456,
    caption: 'Portrait photography session! 👤 #portrait #photography #session',
    comments: 345,
  },
  {
    id: 65,
    username: 'nutrition_facts',
    timeAgo: '2h',
    image: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800',
    likes: 12345,
    caption: 'Nutrition facts you need to know! 🥗 #nutrition #facts #health',
    comments: 234,
  },
  {
    id: 66,
    username: 'landscape_views',
    timeAgo: '10h',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    likes: 34567,
    caption: 'Breathtaking landscape views! 🏔️ #landscape #views #nature',
    comments: 567,
  },
  {
    id: 67,
    username: 'graffiti_art',
    timeAgo: '7h',
    image: 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800',
    likes: 18923,
    caption: 'Amazing graffiti art in the city! 🎨 #graffiti #art #urban',
    comments: 234,
  },
  {
    id: 68,
    username: 'retro_style',
    timeAgo: '4h',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',
    likes: 15678,
    caption: 'Retro style inspiration! 📻 #retro #style #inspiration',
    comments: 234,
  },
  {
    id: 69,
    username: 'contemporary_art',
    timeAgo: '9h',
    image: 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800',
    likes: 23456,
    caption: 'Contemporary art exhibition! 🎭 #contemporary #art #exhibition',
    comments: 345,
  },
  {
    id: 70,
    username: 'street_style',
    timeAgo: '6h',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',
    likes: 18923,
    caption: 'Street style fashion! 👕 #streetstyle #fashion #style',
    comments: 234,
  },
  {
    id: 71,
    username: 'foodie_adventures',
    timeAgo: '3h',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=800',
    likes: 23456,
    caption: 'Foodie adventure continues! 🍜 #foodie #adventure #food',
    comments: 456,
  },
  {
    id: 72,
    username: 'simple_living',
    timeAgo: '8h',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
    likes: 12345,
    caption: 'Simple living philosophy! 🌿 #simple #living #philosophy',
    comments: 234,
  },
  {
    id: 73,
    username: 'graphic_design',
    timeAgo: '5h',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800',
    likes: 23456,
    caption: 'Graphic design portfolio! 🎨 #graphic #design #portfolio',
    comments: 345,
  },
  {
    id: 74,
    username: 'mental_health',
    timeAgo: '2h',
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
    likes: 34567,
    caption: 'Mental health awareness! 🧠 #mentalhealth #awareness #wellness',
    comments: 567,
  },
  {
    id: 75,
    username: 'city_discovery',
    timeAgo: '11h',
    image: 'https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=800',
    likes: 23456,
    caption: 'City discovery adventure! 🌆 #city #discovery #adventure',
    comments: 345,
  },
  {
    id: 76,
    username: 'sustainable_living',
    timeAgo: '6h',
    image: 'https://images.unsplash.com/photo-1466781783364-36c955e42a7f?w=800',
    likes: 15678,
    caption: 'Sustainable living tips! ♻️ #sustainable #living #tips',
    comments: 234,
  },
  {
    id: 77,
    username: 'illustration_art',
    timeAgo: '4h',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800',
    likes: 18923,
    caption: 'Illustration art showcase! ✏️ #illustration #art #showcase',
    comments: 234,
  },
  {
    id: 78,
    username: 'vintage_cars',
    timeAgo: '9h',
    image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
    likes: 34567,
    caption: 'Vintage car collection! 🚗 #vintage #cars #collection',
    comments: 567,
  },
  {
    id: 79,
    username: 'high_end_fashion',
    timeAgo: '5h',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',
    likes: 45678,
    caption: 'High-end fashion showcase! 👠 #highend #fashion #showcase',
    comments: 789,
  },
  {
    id: 80,
    username: 'backpacking_tips',
    timeAgo: '12h',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    likes: 23456,
    caption: 'Backpacking tips for beginners! 🎒 #backpacking #tips #beginners',
    comments: 345,
  },
  {
    id: 81,
    username: 'handmade_goods',
    timeAgo: '7h',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800',
    likes: 12345,
    caption: 'Handmade goods collection! 🧵 #handmade #goods #collection',
    comments: 234,
  },
  {
    id: 82,
    username: 'workout_motivation',
    timeAgo: '3h',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
    likes: 23456,
    caption: 'Workout motivation Monday! 💪 #workout #motivation #monday',
    comments: 456,
  },
  {
    id: 83,
    username: 'art_exhibition',
    timeAgo: '8h',
    image: 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800',
    likes: 34567,
    caption: 'Art exhibition opening night! 🖼️ #art #exhibition #opening',
    comments: 567,
  },
  {
    id: 84,
    username: 'music_discovery',
    timeAgo: '6h',
    image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
    likes: 23456,
    caption: 'New music discovery! 🎧 #music #discovery #new',
    comments: 345,
  },
  {
    id: 85,
    username: 'style_inspiration',
    timeAgo: '4h',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',
    likes: 18923,
    caption: 'Style inspiration for the week! 👗 #style #inspiration #week',
    comments: 234,
  },
  {
    id: 86,
    username: 'gadget_reviews',
    timeAgo: '9h',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800',
    likes: 34567,
    caption: 'Latest gadget review! 📱 #gadget #review #latest',
    comments: 567,
  },
  {
    id: 87,
    username: 'nature_walks',
    timeAgo: '5h',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    likes: 23456,
    caption: 'Nature walk in the park! 🌲 #nature #walk #park',
    comments: 345,
  },
  {
    id: 88,
    username: 'brewery_tours',
    timeAgo: '7h',
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800',
    likes: 15678,
    caption: 'Brewery tour experience! 🍺 #brewery #tour #experience',
    comments: 234,
  },
  {
    id: 89,
    username: 'book_recommendations',
    timeAgo: '3h',
    image: 'https://images.unsplash.com/photo-1489599835382-6746f141f94b?w=800',
    likes: 12345,
    caption: 'Book recommendations for summer! 📖 #books #recommendations #summer',
    comments: 234,
  },
  {
    id: 90,
    username: 'animal_friends',
    timeAgo: '10h',
    image: 'https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=800',
    likes: 34567,
    caption: 'Animal friends meetup! 🐾 #animals #friends #meetup',
    comments: 567,
  },
  {
    id: 91,
    username: 'mindfulness_practice',
    timeAgo: '6h',
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
    likes: 18923,
    caption: 'Mindfulness practice session! 🧘‍♀️ #mindfulness #practice #session',
    comments: 234,
  },
  {
    id: 92,
    username: 'gaming_streams',
    timeAgo: '4h',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800',
    likes: 23456,
    caption: 'Gaming stream tonight! 🎮 #gaming #stream #tonight',
    comments: 456,
  },
  {
    id: 93,
    username: 'chef_secrets',
    timeAgo: '8h',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
    likes: 23456,
    caption: 'Chef secrets revealed! 👨‍🍳 #chef #secrets #cooking',
    comments: 345,
  },
  {
    id: 94,
    username: 'mountain_climbing',
    timeAgo: '1d',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    likes: 45678,
    caption: 'Mountain climbing adventure! ⛰️ #mountain #climbing #adventure',
    comments: 789,
  },
  {
    id: 95,
    username: 'beauty_tutorials',
    timeAgo: '5h',
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800',
    likes: 23456,
    caption: 'Beauty tutorial: Natural makeup look! 💋 #beauty #tutorial #natural',
    comments: 456,
  },
  {
    id: 96,
    username: 'lifestyle_blogger',
    timeAgo: '2h',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
    likes: 18923,
    caption: 'Lifestyle blog update! ✨ #lifestyle #blog #update',
    comments: 234,
  },
  {
    id: 97,
    username: 'creative_workshop',
    timeAgo: '7h',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800',
    likes: 15678,
    caption: 'Creative workshop in progress! 🎨 #creative #workshop #progress',
    comments: 234,
  },
  {
    id: 98,
    username: 'wellness_retreat',
    timeAgo: '9h',
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
    likes: 34567,
    caption: 'Wellness retreat experience! 🧘‍♀️ #wellness #retreat #experience',
    comments: 567,
  },
  {
    id: 99,
    username: 'urban_photography',
    timeAgo: '4h',
    image: 'https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=800',
    likes: 23456,
    caption: 'Urban photography collection! 🏙️ #urban #photography #collection',
    comments: 345,
  },
  {
    id: 100,
    username: 'eco_innovations',
    timeAgo: '6h',
    image: 'https://images.unsplash.com/photo-1466781783364-36c955e42a7f?w=800',
    likes: 18923,
    caption: 'Eco innovations for a better future! 🌍 #eco #innovations #future',
    comments: 234,
  },
];
